document.write("    <meta http-equiv=\"Content-Type\" content=\"text\/html; charset=UTF-8\">");
document.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.write("    <link rel=\"stylesheet\" href=\"http:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/3.3.7\/css\/bootstrap.min.css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/index.css\">");
document.write("    <script src=\"https:\/\/ajax.googleapis.com\/ajax\/libs\/jquery\/1.12.4\/jquery.min.js\"><\/script>");
document.write("    <script src=\"http:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/3.3.7\/js\/bootstrap.min.js\"><\/script>");
document.write("    <link href=\"https:\/\/fonts.googleapis.com\/css?family=Dosis\" rel=\"stylesheet\">");
document.write("<link rel=\"icon\" ");
document.write("      type=\"image\/png\" ");
document.write("      href=\"img\/fav.png\">");
document.write("    <title>BidBox | Bid&Buy<\/title>");
document.write("<nav class=\"navbar navbar-default\">");
document.write("    <div class=\"container-fluid\">");
document.write("");
document.write("        <div id=\"triangle-topleft\">");
document.write("        <img  class=\"penguin\" src=\"img\/peng.png\" height=\"130\" width=\"285\" ><\/div>");
document.write("");
document.write("    <\/div>");
document.write("<\/nav>");
