document.write("");
document.write("    <meta http-equiv=\"Content-Type\" content=\"text\/html; charset=UTF-8\">");
document.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.write("    <link rel=\"stylesheet\" href=\"http:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/3.3.7\/css\/bootstrap.min.css\">");
document.write("    <link rel=\"stylesheet\" href=\".\/..\/css\/index.css\">");
document.write("    <script src=\"https:\/\/ajax.googleapis.com\/ajax\/libs\/jquery\/1.12.4\/jquery.min.js\"><\/script>");
document.write("    <script src=\"http:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/3.3.7\/js\/bootstrap.min.js\"><\/script>");
document.write("    <link href=\"https:\/\/fonts.googleapis.com\/css?family=Dosis\" rel=\"stylesheet\">");
document.write("    <title>BidBox | Bid&Buy<\/title>");
document.write("    <nav class=\"navbar navbar-default navbar-static-top\">");
document.write("        <div class=\"container-fluid\">");
document.write("");
document.write("            <div id=\"triangle-topleft\">");
document.write("                <img  class=\"penguin\" src=\"img\/peng.png\" height=\"130\" width=\"285\" >");
document.write("            <\/div>");
document.write("");
document.write("");
document.write("");
document.write("                    <ul class=\"nav  nav-pills navbar-right\">");
document.write("                    <li class=\"active\"><a href=\"#\">Home<\/a><\/li>");
document.write("                    <li><a href=\"#\">My Auctions<\/a><\/li>");
document.write("                    <li><a href=\".\/..\/welcome\/search.jsp\">Search Auctions<\/a><\/li>");
document.write("                    <li><a href=\".\/..\/seller\/add_auction.jsp\">Add Auction<\/a><\/li>");
document.write("                    <li><a href=\"#\">About us<\/a><\/li>");
document.write("                    <li><a href=\"#\">Log out<\/a><\/li>    ");
document.write("                    <\/ul>");
document.write("");
document.write("");
document.write("        <\/div>");
document.write("");
document.write("    <\/nav>");
document.write("");
